name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request'}}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mathi
        tags: latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
