name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["codeql"]
    branches: main
    types: completed

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
	- uses: actions/setup-node@v3
      with:
        node-version: latest

    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mathi
        tags: latest
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}